/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game.numberguessinggame;

import javax.swing.JOptionPane;

/**
 *
 * @author Hp
 */
public class GamingFrame extends javax.swing.JFrame {

    /**
     * Creates new form GamingFrame
     */
    int compnum=0; 
    String str2= "";
    public GamingFrame() {
        initComponents();
        super.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtNo = new javax.swing.JTextField();
        btnGuess = new javax.swing.JButton();
        lblShowNo = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        btnQuit = new javax.swing.JButton();
        lblCount = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        jLabel1.setText("NUMBER GUESSING GAME");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 450, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 51, 51));
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 480, 70));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 51));
        jLabel2.setText("Enter the Number Between 1 and 100");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 500, -1));

        txtNo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtNo.setForeground(new java.awt.Color(0, 51, 255));
        jPanel1.add(txtNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 180, 40));

        btnGuess.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnGuess.setText("Guess");
        btnGuess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuessActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuess, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, -1, -1));

        lblShowNo.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lblShowNo.setText("Show Number :");
        lblShowNo.setEnabled(false);
        lblShowNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblShowNoMouseClicked(evt);
            }
        });
        jPanel1.add(lblShowNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 560, 40));

        lblStatus.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lblStatus.setText("Status:");
        jPanel1.add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 570, 40));

        btnQuit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnQuit.setText("QUIT");
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });
        jPanel1.add(btnQuit, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, -1, -1));

        lblCount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCount.setText("Attempt");
        jPanel1.add(lblCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 838, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuessActionPerformed
        // TODO add your handling code here: 
        try
        {
            String str = txtNo.getText().trim();
            int UserNo = Integer.parseInt(str);
        if (UserNo <= 0 || UserNo > 100 )
        {
            lblStatus.setText("Invalid Guess");
        }
        else if (UserNo == compnum)
        {
            lblStatus.setText("Your Guess is correct !!!");
            
        }
        else if (UserNo > compnum)
        {
            lblStatus.setText("Your Guess is Too High !!!");
        }

        else if (UserNo < compnum)
        {
            lblStatus.setText("Your Guess is Too Low !!!");
        }
        else
        {
            lblStatus.setText("Your Guess is incorrect !!!");
        }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null,"Please input Number between 1 and 100");
        }
    }//GEN-LAST:event_btnGuessActionPerformed

    private void lblShowNoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShowNoMouseClicked
        // TODO add your handling code here:
        compnum = (int) (Math.random()*100 +1);
        str2 = Integer.toString(compnum);
        lblShowNo.setText(str2);
    }//GEN-LAST:event_lblShowNoMouseClicked

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        // TODO add your handling code here:
        int ans;
        ans=JOptionPane.showConfirmDialog(null,"Are you to Quit ?","Quitting!",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(ans==JOptionPane.YES_OPTION)
        {
            String name=JOptionPane.showInputDialog(null,"Enter Your name","Input name",JOptionPane.INFORMATION_MESSAGE);
            //name=name.trim();
            String message="for using this Game!";
            if(name!=null && name.isEmpty()==false)
            message="Thank you "+name+" "+message;
            else
            message="Thank you user "+message;
            JOptionPane.showMessageDialog(null, message,"Good Day!",JOptionPane.INFORMATION_MESSAGE);

            System.exit(0);
        }
    }//GEN-LAST:event_btnQuitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GamingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GamingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GamingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GamingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GamingFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuess;
    private javax.swing.JButton btnQuit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JLabel lblCount;
    private javax.swing.JLabel lblShowNo;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTextField txtNo;
    // End of variables declaration//GEN-END:variables
}
